version: "3.7"

services:
  trade:
    build:
      context: ./trade
    ports:
      - "8008:8008"
    restart: always
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - .:/usr/src/trade
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8008"
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=trade-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5001:5432"

volumes:
  postgres_data:
