version: "3.7"

services:
  trade:
    build:
      context: .
    ports:
      - "8008:8008"
    restart: always
    volumes:
      - .:/trade
    environment:
      - DB_HOST=db
      - DB_NAME=trade-dev
      - DB_USER=postgres
      - DB_PASS=root
      - DB_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8008"
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=trade-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5001:5432"
